M48
; DRILL file {KiCad 8.0.8} date 2025-03-13T11:37:34-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-13T11:37:34-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.100
%
G90
G05
T1
X138.99Y-66.25
X138.99Y-69.25
T2
X115.0Y-48.0
X115.0Y-119.8
X197.85Y-119.8
X198.15Y-47.95
M30
